:;#---------------------------------------------------------------------
:;#---                                                              ----
:;#--- PlTbUtils Script for generating test files                   ----
:;#--- For Windows and Linux. Line endings must be LF (Unix).       ----
:;#---                                                              ----
:;#--- This file is part of the PlTbUtils project                   ----
:;#--- http://opencores.org/project,pltbutils                       ----
:;#---                                                              ----
:;#--- Description:                                                 ----
:;#--- PlTbUtils is a collection of functions, procedures and       ----
:;#--- components for easily creating stimuli and checking response ----
:;#--- in automatic self-checking testbenches.                      ----
:;#---                                                              ----
:;#--- This file generates test files for verifying the file check  ----
:;#--- procedures check_binfile, check_txtfile, check_datfile, etc. ----
:;#--- In tb_pltbutils.vhd, there are tests that let these          ----
:;#--- procedures compare test files (the ones generated by this    ----
:;#--- script).                                                     ----
:;#---                                                              ----
:;#--- To Do:                                                       ----
:;#--- -                                                            ----
:;#---                                                              ----
:;#--- Author(s):                                                   ----
:;#--- - Per Larsson, pela.opencores@gmail.com                      ----
:;#---                                                              ----
:;#---------------------------------------------------------------------
:;#---                                                              ----
:;#--- Copyright (C) 2020 Authors and OPENCORES.ORG                 ----
:;#---                                                              ----
:;#--- This source file may be used and distributed without         ----
:;#--- restriction provided that this copyright statement is not    ----
:;#--- removed from the file and that any derivative work contains  ----
:;#--- the original copyright notice and the associated disclaimer. ----
:;#---                                                              ----
:;#--- This source file is free software; you can redistribute it   ----
:;#--- and/or modify it under the terms of the GNU Lesser General   ----
:;#--- Public License as published by the Free Software Foundation; ----
:;#--- either version 2.1 of the License, or (at your option) any   ----
:;#--- later version.                                               ----
:;#---                                                              ----
:;#--- This source is distributed in the hope that it will be       ----
:;#--- useful, but WITHOUT ANY WARRANTY; without even the implied   ----
:;#--- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR      ----
:;#--- PURPOSE. See the GNU Lesser General Public License for more  ----
:;#--- details.                                                     ----
:;#---                                                              ----
:;#--- You should have received a copy of the GNU Lesser General    ----
:;#--- Public License along with this source; if not, download it   ----
:;#--- from http://www.opencores.org/lgpl.shtml                     ----
:;#---                                                              ----
:;#---------------------------------------------------------------------

tclsh gen_testfiles.tcl
